name: 'chw_activity_project'
version: '1.0.0'
config-version: 2

profile: 'chw_activity_project'

model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analysis"]
test-paths: ["tests"]

target-path: "target"
clean-targets: ["target", "dbt_modules"]

models:
  chw_activity_project:
    +materialized: view
